name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., latest, v1.0.0)'
        required: true
        default: 'latest'
      image_path:
        description: 'Path for the Docker image (e.g., ms, myapp)'
        required: true
        default: 'ms'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '6.x'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repository name
        id: repo_names
        run: |
          echo "repo_name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        env:
          DOCKER_BUILDKIT: 1 # for build cache
        run: |
          docker build \
          -t ghcr.io/${{ github.repository_owner }}/${{ steps.repo_name.outputs.repo_name }}/${{ github.event.inputs.image_path }}:${{ github.event.inputs.image_tag }} \
          -f ${{ github.event.inputs.image_path }}/Dockerfile \
          ${{ github.event.inputs.image_path }}

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ steps.repo_name.outputs.repo_name }}/${{ github.event.inputs.image_path }}:${{ github.event.inputs.image_tag }}