apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms
  labels:
    app: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms
  template:
    metadata:
      labels:
        app: ms
    spec:
      containers:
      - name: ms-app
        image: ghcr.io/tingwei628/ms/ms:latest
        ports:
        - containerPort: 10001
        env:
        - name: DOTNET_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__PgCluster
          valueFrom:
            secretKeyRef:
              name: ms-dev-secret
              key: pg-cluster
        - name: ASPNETCORE_URLS
          value: http://+:10001
        livenessProbe:
          httpGet:
            path: /health
            port: 10001
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 10001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ms-service
  labels:
    app: ms
spec:
  selector:
    app: ms
  ports:
    - port: 10001
      targetPort: 10001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ms-ingress
  namespace: default
  labels:
    app: ms
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`172.19.0.6`) && PathPrefix(`/ms`)
      kind: Rule
      middlewares:
        - name: strip-ms-prefix
      services:
        - name: ms-service
          port: 10001
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-ms-prefix
  labels:
    app: ms
spec:
  stripPrefix:
    prefixes:
      - /ms